# Generated by Django 2.2.16 on 2021-12-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211209_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте картинку', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
